00_hello: 00_hello.cpp
	mpicxx 00_hello.cpp
	mpirun -np 4 ./a.out
01_nbody: 01_nbody.cpp
	mpicxx 01_nbody.cpp
	mpirun -np 4 ./a.out
02_split: 02_split.cpp
	mpicxx 02_split.cpp
	mpirun -np 4 ./a.out
03_gather: 03_gather.cpp
	mpicxx 03_gather.cpp
	mpirun -np 4 ./a.out
04_bcast: 04_bcast.cpp
	mpicxx 04_bcast.cpp
	mpirun -np 4 ./a.out
05_allgather: 05_allgather.cpp
	mpicxx 05_allgather.cpp
	mpirun ./a.out
06_iloop: 06_iloop.cpp
	mpicxx 06_iloop.cpp
	mpirun -np 4 ./a.out
07_jloop: 07_jloop.cpp
	mpicxx 07_jloop.cpp
	mpirun -np 4 ./a.out
08_derived_gather: 08_derived_gather.cpp
	mpicxx 08_derived_gather.cpp
	mpirun -np 4 ./a.out
09_derived_reduce: 09_derived_reduce.cpp
	mpicxx 09_derived_reduce.cpp
	mpirun -np 4 ./a.out
10_ring: 10_ring.cpp
	mpicxx 10_ring.cpp
	mpirun -np 4 ./a.out
11_distributed: 11_distributed.cpp
	mpicxx 11_distributed.cpp
	mpirun -np 4 ./a.out
12_non_blocking: 12_non_blocking.cpp
	mpicxx 12_non_blocking.cpp
	mpirun -np 4 ./a.out
13_one_sided: 13_one_sided.cpp
	mpicxx 13_one_sided.cpp
	mpirun -np 4 ./a.out
