10_cavity: 10_cavity.cpp
	g++ 10_cavity.cpp

10_cavity_openmp: 10_cavity_openmp.cpp
	g++ 10_cavity_openmp.cpp -fopenmp

10_cavity_mpi: 10_cavity_mpi.cpp
	mpicxx 10_cavity_mpi.cpp

10_cavity_openacc: 10_cavity_openacc.cpp
	nvc++ 10_cavity_openacc.cpp -acc -gpu=managed -Minfo
